apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
data:
  AUTH_GRPC_URL: auth-service:50051
  LISTING_GRPC_URL: listing-service:50052
  RESERVATION_GRPC_URL: reservation-service:50053