// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v6.30.1
// source: proto/reservation.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "reservation";

export interface IncludeListing {
  listing?: boolean | undefined;
}

export interface DeleteOptionDto {
  reservationId?: number | undefined;
  userId?: string | undefined;
}

export interface ReservationOptionDto {
  listingId?: number | undefined;
  userId?: string | undefined;
  listing?: ListingFilter | undefined;
  include?: IncludeListing | undefined;
}

export interface DeleteReservationDto {
  message: string;
}

export interface ReservationIdDto {
  reservationId: number;
}

export interface ListingFilter {
  userId?: string | undefined;
}

export interface ReservationsDto {
  reservations: ReservationDto[];
}

export interface CreateReservationDto {
  userId: string;
  listingId: number;
  startDate: string;
  endDate: string;
  totalPrice: number;
}

export interface ReservationDto {
  id: number;
  userId: string;
  listingId: number;
  startDate: string;
  endDate: string;
  totalPrice: number;
  createdAt: string;
  listing?: ListingResponseDto | undefined;
}

export interface ListingResponseDto {
  id: number;
  title: string;
  description: string;
  imageSrc: string;
  category: string;
  roomCount: number;
  bathroomCount: number;
  guestCount: number;
  locationValue: string;
  userId: string;
  price: number;
  createdAt?: string | undefined;
  user?: User | undefined;
}

export interface User {
  id?: string | undefined;
  name?: string | undefined;
  email?: string | undefined;
  emailVerified?: string | undefined;
  image?: string | undefined;
  hashedPassword?: string | undefined;
  favoriteIds: number[];
  createdAt?:
    | string
    | undefined;
  /** repeated Account accounts = 10;   // User can have multiple accounts */
  updatedAt?: string | undefined;
}

export const RESERVATION_PACKAGE_NAME = "reservation";

export interface ReservationServiceClient {
  createReservation(request: CreateReservationDto): Observable<ReservationDto>;

  getReservationById(request: ReservationIdDto): Observable<ReservationDto>;

  getReservationByOption(request: ReservationOptionDto): Observable<ReservationsDto>;

  deleteReservationById(request: ReservationIdDto): Observable<DeleteReservationDto>;

  deleteReservationsByOption(request: DeleteOptionDto): Observable<DeleteReservationDto>;
}

export interface ReservationServiceController {
  createReservation(
    request: CreateReservationDto,
  ): Promise<ReservationDto> | Observable<ReservationDto> | ReservationDto;

  getReservationById(request: ReservationIdDto): Promise<ReservationDto> | Observable<ReservationDto> | ReservationDto;

  getReservationByOption(
    request: ReservationOptionDto,
  ): Promise<ReservationsDto> | Observable<ReservationsDto> | ReservationsDto;

  deleteReservationById(
    request: ReservationIdDto,
  ): Promise<DeleteReservationDto> | Observable<DeleteReservationDto> | DeleteReservationDto;

  deleteReservationsByOption(
    request: DeleteOptionDto,
  ): Promise<DeleteReservationDto> | Observable<DeleteReservationDto> | DeleteReservationDto;
}

export function ReservationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createReservation",
      "getReservationById",
      "getReservationByOption",
      "deleteReservationById",
      "deleteReservationsByOption",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReservationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReservationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RESERVATION_SERVICE_NAME = "ReservationService";
