apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: homybnb-cluster
  region: us-east-1

vpc:
  id: vpc-0c112c28c67aaccec
  subnets:
    public:
      public-subnet-1:
        id: subnet-04295cdcd3c22948b
      public-subnet-2:
        id: subnet-07b845756de15641a
  securityGroup: sg-09a6f8e953f97d3d2

managedNodeGroups:
- name: homybnb-nodegroup
  instanceType: t3.medium
  desiredCapacity: 3
  minSize: 2
  maxSize: 4