apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
        - name: listing-service
          image: qthais/ms-listing-homybnb:2.0
          envFrom:
            - configMapRef:
                name: listing-config
            - secretRef:
                name: listing-secret
          ports:
            - containerPort: 50052
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing-service
  ports:
    - port: 50052
      targetPort: 50052
