apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  JWT_ACCESS_SECRET: your jwt secret | base64
  JWT_REFRESH_SECRET: your refresh secret | base64
  DATABASE_URL: your auth database url | base64

