name: BE Workflow

# Trigger on push to any branch or pull requests targeting 'main' branch
on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting 'main'
    paths:
      - 'backend/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - apigateway
          - auth
          - listing
          - reservation
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the version of Node.js you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
            cd backend
            npm install

      # Step 4: Run tests
      - name: Run tests
        run: |
            cd backend
            npx prisma generate --schema=apps/auth/prisma/schema.prisma
            npx prisma generate --schema=apps/listing/prisma/schema.prisma
            npx prisma generate --schema=apps/reservation/prisma/schema.prisma
            npm run test
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/apps/${{ matrix.service }}
          push: true
          tags: qthais/ms-${{ matrix.service }}-homybnb:latest